
package gov.nih.nlm.uts.webservice.metadata;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UtsWsMetadataControllerImplService", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", wsdlLocation = "https://uts-ws.nlm.nih.gov/services/nwsMetadata?wsdl")
public class UtsWsMetadataControllerImplService
    extends Service
{

    private final static URL UTSWSMETADATACONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UTSWSMETADATACONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName UTSWSMETADATACONTROLLERIMPLSERVICE_QNAME = new QName("http://webservice.uts.umls.nlm.nih.gov/", "UtsWsMetadataControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://uts-ws.nlm.nih.gov/services/nwsMetadata?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTSWSMETADATACONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        UTSWSMETADATACONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public UtsWsMetadataControllerImplService() {
        super(__getWsdlLocation(), UTSWSMETADATACONTROLLERIMPLSERVICE_QNAME);
    }

    public UtsWsMetadataControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns UtsWsMetadataController
     */
    @WebEndpoint(name = "UtsWsMetadataControllerImplPort")
    public UtsWsMetadataController getUtsWsMetadataControllerImplPort() {
        return super.getPort(new QName("http://webservice.uts.umls.nlm.nih.gov/", "UtsWsMetadataControllerImplPort"), UtsWsMetadataController.class);
    }

    private static URL __getWsdlLocation() {
        if (UTSWSMETADATACONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw UTSWSMETADATACONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return UTSWSMETADATACONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
