
package gov.nih.nlm.uts.webservice.finder;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.0
 * 
 */
@WebServiceClient(name = "UtsWsFinderControllerImplService", targetNamespace = "http://webservice.uts.umls.nlm.nih.gov/", wsdlLocation = "https://uts-ws.nlm.nih.gov/services/nwsFinder?wsdl")
public class UtsWsFinderControllerImplService
    extends Service
{

    private final static URL UTSWSFINDERCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException UTSWSFINDERCONTROLLERIMPLSERVICE_EXCEPTION;
    private final static QName UTSWSFINDERCONTROLLERIMPLSERVICE_QNAME = new QName("http://webservice.uts.umls.nlm.nih.gov/", "UtsWsFinderControllerImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("https://uts-ws.nlm.nih.gov/services/nwsFinder?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        UTSWSFINDERCONTROLLERIMPLSERVICE_WSDL_LOCATION = url;
        UTSWSFINDERCONTROLLERIMPLSERVICE_EXCEPTION = e;
    }

    public UtsWsFinderControllerImplService() {
        super(__getWsdlLocation(), UTSWSFINDERCONTROLLERIMPLSERVICE_QNAME);
    }

    public UtsWsFinderControllerImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    /**
     * 
     * @return
     *     returns UtsWsFinderController
     */
    @WebEndpoint(name = "UtsWsFinderControllerImplPort")
    public UtsWsFinderController getUtsWsFinderControllerImplPort() {
        return super.getPort(new QName("http://webservice.uts.umls.nlm.nih.gov/", "UtsWsFinderControllerImplPort"), UtsWsFinderController.class);
    }

    private static URL __getWsdlLocation() {
        if (UTSWSFINDERCONTROLLERIMPLSERVICE_EXCEPTION!= null) {
            throw UTSWSFINDERCONTROLLERIMPLSERVICE_EXCEPTION;
        }
        return UTSWSFINDERCONTROLLERIMPLSERVICE_WSDL_LOCATION;
    }

}
